#!/bin/bash

usage() {
    echo "USAGE: `basename $0` [start|stop|restart]"
}

start() {
    echo "Starting the snotify daemon"
    snotifyd&
    snotify-capslockd&
}

stop() {
    # Kill the snotify daemon
    pidfile=/tmp/snotifyd.pid
    if [ -f ${pidfile} ]; then
        echo "Stopping the snotify daemon"
        kill -9 `cat ${pidfile}`
    else
        echo "Snotify daemon does not seem to be running"
    fi

    # Kill the snotify capslock daemon
    pidfile=/tmp/snotify-capslockd.pid
    if [ -f ${pidfile} ]; then
        echo "Stopping the capslock daemon"
        kill -9 `cat ${pidfile}`
    else
        echo "Snotify capslock daemon does not seem to be running"
    fi
}


if [ $# -le 0 ]; then
    usage
    exit 1
fi

case $1 in
    start) start ;;
    stop) stop ;;
    restart)
        stop
        start
        ;;
    *) usage ;;
esac
